### ISSUE TITLE
Config could be a map.

### ISSUE THREAD

**Issue by ticking** [gorillalabs/sparkling#10]
Hey,
I was wondering if it wasn't more clojuresque to provide the configuration as a hashmap,
instead of building it up.

A very very early version of clj-spark had it implemented that way.

**Comment by chrisbetz** [comment]
flambo and sparkling just copied that - you still can do both:

(defn set
  ([conf key val]
     ...)
  ([conf amap]
    ...))

So, feel free to use it the way you like it the most.
