### ISSUE TITLE
Spark MLlib support?

### ISSUE THREAD

**Issue by davidiba** [gorillalabs/sparkling#14]
Is there support for using the spark MLlib (machine learning) API?  If not, any plans to support this or alternate clojure libraries to do this? Thanks, -David

**Comment by chrisbetz** [comment]
Hi,

I’m not currently using spark MLlib, making it hard to create and test the code. There are others who also asked, and I’m not sure if there is some progress towards it from the community. You might want to contact Bruce from Mastodon C (https://twitter.com/otfrom <https://twitter.com/otfrom>), he’s using sparkling and tweeted about mllib.

So sorry, it will take some more time from my side.

If you would like to contribute, you’re very welcome and I would happily take PRs for it ;)

Happy Easter break,

Chris

**Comment by shark8me** [comment]
I've added support for the classification part of Spark's MLLib, in pull request #43

**Comment by chrisbetz** [comment]
pull request merged, closing this issue.
