### ISSUE TITLE
Serializer issues while running on Mesos

### ISSUE THREAD

**Issue by prasincs** [gorillalabs/sparkling#18]
I'm running into `spark.serialization.Registrator` issues with Kyro when running Sparkling on Mesos 

```
task 0.3 in stage 0.0 (TID 3, test-server): java.io.IOException: org.apache.spark.SparkException: Failed to register classes with Kryo
        at org.apache.spark.util.Utils$.tryOrIOException(Utils.scala:1155)
        at org.apache.spark.broadcast.TorrentBroadcast.readBroadcastBlock(TorrentBroadcast.scala:164)
        at org.apache.spark.broadcast.TorrentBroadcast._value$lzycompute(TorrentBroadcast.scala:64)
        at org.apache.spark.broadcast.TorrentBroadcast._value(TorrentBroadcast.scala:64)
        at org.apache.spark.broadcast.TorrentBroadcast.getValue(TorrentBroadcast.scala:87)
        at org.apache.spark.broadcast.Broadcast.value(Broadcast.scala:70)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:58)
        at org.apache.spark.scheduler.Task.run(Task.scala:64)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:203)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.spark.SparkException: Failed to register classes with Kryo
        at org.apache.spark.serializer.KryoSerializer.newKryo(KryoSerializer.scala:101)
        at org.apache.spark.serializer.KryoSerializerInstance.<init>(KryoSerializer.scala:153)
        at org.apache.spark.serializer.KryoSerializer.newInstance(KryoSerializer.scala:115)
        at org.apache.spark.broadcast.TorrentBroadcast$.unBlockifyObject(TorrentBroadcast.scala:214)
        at org.apache.spark.broadcast.TorrentBroadcast$$anonfun$readBroadcastBlock$1.apply(TorrentBroadcast.scala:177)
        at org.apache.spark.util.Utils$.tryOrIOException(Utils.scala:1152)
        ... 11 more
Caused by: java.lang.ClassNotFoundException: sparkling.serialization.Registrator
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at org.apache.spark.serializer.KryoSerializer$$anonfun$newKryo$3.apply(KryoSerializer.scala:97)
        at org.apache.spark.serializer.KryoSerializer$$anonfun$newKryo$3.apply(KryoSerializer.scala:97)
        at scala.Option.map(Option.scala:145)
        at org.apache.spark.serializer.KryoSerializer.newKryo(KryoSerializer.scala:97)
        ... 16 more
```

The configuration is as follows --
```
(defn make-spark-context []
  (let [c (-> (conf/spark-conf)
              (conf/master "mesos://zk://zk0:2181,zk1:2181,zk2:2181/mesos")
              (conf/app-name "test-app")
              (conf/set "spark.executor.uri" "hdfs://hadoop-namenode/spark/spark-1.3.0-bin-hadoop2.3.tgz")
              (conf/set "spark.ui.port" "5555")
              (conf/set "spark.home" "/usr/lib/spark/spark-1.3.0-bin-hadoop2.3"))]
    (spark/spark-context c)))
```

I'm reading a gzipped text file from a hdfs storage. 
```
(let [sc (make-spark-context)
       file-rdd (spark/text-file "hdfs://hadoop-namenode/example/test.gz")]
     (println (.first file-rdd)))
```

This works fine when the master is set to `"local[*]"`

**Comment by chrisbetz** [comment]
Hi,
as I mentioned in the Readme (https://github.com/gorillalabs/sparkling/blob/master/README.md) you have to make sure that the sparkling.serizalization namespace gets AOT-compiled.
You can achieve this by adding
:aot [#".*" sparkling.serialization sparkling.destructuring]
to your project.clj.
However, as you're not the first one to stumble upon that issue, I'll try to find a better way to deal with this issue for the next release.
Cheers,
Chris

**Comment by prasincs** [comment]
@chrisbetz I'm invoking this from a ring route, and ring is unhappy with aot (most of the time).. so I'm selectively doing aot on classes. It looks like this on my project.clj 
```
 :aot [clojure.tools.logging.impl sparkling.serialization sparkling.destructuring]

  :main ^:skip-aot exampleproject.core
```

I'll probably spend a little bit more time and cleanup namespaces and try again but sharing this in case it's a known issue.

**Comment by prasincs** [comment]
Looks like it works for me on Mesos when I initialize the context without kryo. Somehow the slaves don't initialize the classes properly.

**Comment by chrisbetz** [comment]
Seems to be fine for now. I'll close this, just drop me a note if you need further assistance.

Cheers,

Chris

**Comment by hellonico** [comment]
Sorry for ping here again.
I can't get sparkling to run on mesos, 
Connection to the master is ok, but I get serialization errors.


```clojure
(defn new-spark-context []
  (let [c (-> (s-conf/spark-conf)
              (s-conf/master master)
              (s-conf/app-name "sparkling")
              (s-conf/set "spark.akka.timeout" "300")
              ;(s-conf/set "spark.serializer" "org.apache.spark.serializer.JavaSerializer")
              (s-conf/set "spark.mesos.executor.home" "/Users/niko/Downloads//spark-1.3.1-bin-hadoop2.4")
              (s-conf/set "spark.executor.uri" "http://localhost/spark-1.3.1-bin-hadoop2.4.tgz")
              (s-conf/set conf)
              (s-conf/set-executor-env env))]
    (s/spark-context c) ))
```

And that is my favorite stacktrace:

```
Caused by: org.apache.spark.SparkException: Failed to register classes with Kryo
	at org.apache.spark.serializer.KryoSerializer.newKryo(KryoSerializer.scala:101)
	at org.apache.spark.serializer.KryoSerializerInstance.<init>(KryoSerializer.scala:153)
	at org.apache.spark.serializer.KryoSerializer.newInstance(KryoSerializer.scala:115)
	at org.apache.spark.broadcast.TorrentBroadcast$.unBlockifyObject(TorrentBroadcast.scala:214)
	at org.apache.spark.broadcast.TorrentBroadcast$$anonfun$readBroadcastBlock$1.apply(TorrentBroadcast.scala:177)
	at org.apache.spark.util.Utils$.tryOrIOException(Utils.scala:1153)
	... 12 more
Caused by: java.lang.ClassNotFoundException: sparkling.serialization.Registrator
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
```

This is the relevant part of project.clj

```clojure
:jvm-opts ["-Xmx2G" ~(str "-Djava.library.path=/usr/local/Cellar/mesos/0.22.1/lib/:" (System/getenv "LD_LIBRARY_PATH"))]
  :dependencies [[org.clojure/clojure "1.6.0"]
                 [gorillalabs/sparkling "1.2.2"]
                 [org.apache.spark/spark-core_2.10 "1.3.1"]
                 [clj-time "0.8.0"]
                 [org.clojure/tools.trace "0.7.8"]
                 [clj-glob "1.0.0"]
                 [com.brainbot/iniconfig "0.2.0"]]
  :aot [#".*" sparkling.serialization sparkling.destructuring]
  :main ^:skip-aot  sparkling-example.core
```

**Comment by chrisbetz** [comment]
Could you please unpack your jar (or list the contents of your jar) and
make sure that sparkling.serialization really is AOT-compiled?

This should look similar to this:

*✗* jar tvf target/XXX-standalone.jar | grep
'sparkling/serialization$register'

  2613 Mon Jul 06 12:57:00 CEST 2015 *sparkling/serialization$register*
.class

  2420 Mon Jul 06 12:57:00 CEST 2015 *sparkling/serialization$register*
_array_type.class

  2860 Mon Jul 06 12:57:00 CEST 2015 *sparkling/serialization$register*
_base_classes.class

   794 Mon Jul 06 12:57:00 CEST 2015 *sparkling/serialization$register*
_class.class

   879 Mon Jul 06 12:57:00 CEST 2015 *sparkling/serialization$register*
_class_with_id.class

   937 Mon Jul 06 12:57:00 CEST 2015 *sparkling/serialization$register*
_class_with_serializer.class

  1076 Mon Jul 06 12:57:00 CEST 2015 *sparkling/serialization$register*
_class_with_serializer_and_id.class

  1223 Mon Jul 06 12:57:00 CEST 2015 *sparkling/serialization$register*
_clojure.class

  2244 Mon Jul 06 12:57:00 CEST 2015 *sparkling/serialization$register*
_java_class_serializers.class

  1430 Mon Jul 06 12:57:00 CEST 2015 *sparkling/serialization$register*
_native_array_serializers.class

   809 Mon Jul 06 12:57:00 CEST 2015 *sparkling/serialization$register*
_optional$fn__6358.class

  1236 Mon Jul 06 12:57:00 CEST 2015 *sparkling/serialization$register*
_optional.class

  2457 Mon Jul 06 12:57:00 CEST 2015 *sparkling/serialization$register*
_scala.class

  1921 Mon Jul 06 12:57:00 CEST 2015 *sparkling/serialization$register*
_spark.class

If not, you're disabling aot compilation in your lein project.clj.

Please post more on this if you need further help.

Cheers,

Chris

**Comment by chrisbetz** [comment]
Or are you trying to connect a local REPL (without AOT) to a cluster?

**Comment by hellonico** [comment]
I am trying to connect to the cluster directly.

**Comment by chrisbetz** [comment]
Ok, then you need to make sure you AOT-compile the 'required' stuff.

I usually comp. everything to go to cluster, using repl-conn to cluster for analysis, but local Spark master for dev.

Cheers, Chris

**Comment by hellonico** [comment]
- nico
On 月, 7月 6, 2015 at 9:36 午後, chris_betz <notifications@github.com> wrote:
Ok, then you need to make sure you AOT-compile the 'required' stuff.

I usually comp. everything to go to cluster, using repl-conn to cluster for
analysis, but local Spark master for dev.

Cheers, Chris



> Am 06.07.2015 um 13:37 schrieb Nicolas Modrzyk <notifications@github.com>:
>
> I am trying to connect to the cluster directly.
>
> —
> Reply to this email directly or view it on GitHub.
>
—
Reply to this email directly or view it on GitHub
[https://github.com/gorillalabs/sparkling/issues/18#issuecomment-118841106] .[https://github.com/notifications/beacon/AAAofZuKKlipPqKLvIYo3-ALgMmTA3mOks5oam3dgaJpZM4ER1G0.gif]

**Comment by chrisbetz** [comment]
I think there's something missing ;)



> Am 06.07.2015 um 14:38 schrieb Nicolas Modrzyk <notifications@github.com>:
> 
> - nico

**Comment by hellonico** [comment]
Yes indeed .. ;) Sorry.

Thanks to your directions I could get the jar file to run on mesos properly as well using spark-submit with the master settings on the mesos environment.

But I was hoping to get a chance to deploy the job straight from the REPL just like spark-console can doing it. 
Is there anyway to pre-deploy the jar and classes or something ? I am not sure why it is not finding the classes. 

Any idea about what to try  ?

**Comment by chrisbetz** [comment]
Hi,

that's acutally the thing I need to write a seperate tutorial for, because
this question arises so often ;)

The thing is, you need to start the REPL from inside of your driver and
then connect to that (remote) nrepl server.

Just use clojure.tools.nrepl for that (see
https://github.com/clojure/tools.nrepl) and remember to secure your REPL
(e.g. by only binding to 127.0.0.1 and ssh-tunneling there).

That way, you can use the repl to interactively dive into your Spark stuff.
But be aware: If things are serialized by Spark, your functions need to be
AOT compiled. I usually have a set of debugging functions in a separate
namespace (usually used inside spark filters) to work inside Spark jobs,
then I take some data from the RDDs computed and process them in "regular"
clojure where functions can be redefined.

It's not as elegant as the spark-shell, where you could add arbitrary code,
but that has special hooks inside Spark to alter classloading. Diving
deeper into that might become handy, but takes too much effort for me to
follow along that route.

You might also want to have a look on
https://github.com/gorillalabs/gorilla-repl (my fork of the GorillaREPL
repo, see here for rational:
https://github.com/JonyEpsilon/gorilla-repl/pull/220), because this is what
I use to connect to my Spark REPL. To fully take advantage from this, you
will need to add a the GorillaREPL middleware to your nrepl using something
like this in your project.clj

;; > this is for the gorilla-repl feature
[gorilla-renderable "1.0.0"]
[gorilla-repl "0.3.4" :exclusions [org.clojure/clojure
                                   http-kit
                                   ring/ring-json
                                   cheshire
                                   compojure
                                   org.slf4j/slf4j-api
                                   ch.qos.logback/logback-classic
                                   gorilla-renderable
                                   org.clojure/data.codec
                                   javax.servlet/servlet-api
                                   grimradical/clj-semver
                                   clojure-complete]
 ;; < end of gorilla-repl dependencies


and

(ns ...

(:require [clojure.tools.nrepl.server :as nrepl-server]

           [gorilla-repl.render-values-mw :as gorillarepl-mw]
            ;; it's essential this import comes after the previous one! It
           ;; refers directly to a var in nrepl (as a hack to workaround
           ;; a weakness in nREPL's middleware resolution).

            [cider.nrepl :as cider]
            [gorilla-repl.renderer]
           )

...)


(defn start [nrepl-config]
  (let [cider-mw (map resolve cider/cider-middleware)
        middleware (conj cider-mw #'gorillarepl-mw/render-values)
        gorillarepl-handler (apply nrepl-server/default-handler middleware)]
    (nrepl-server/start-server :port (:port nrepl-config 0)
                               :bind (:bind nrepl-config "127.0.0.1")
                               :handler gorillarepl-handler)))


to trigger your nrepl-server.


Hope that helps


Cheers,


Chris

**Comment by borgesgabriel** [comment]
to anyone who stumbles onto the `java.lang.ClassNotFoundException: sparkling.serialization.Registrator` issue but whose `:aot` entry in `project.clj` already contains the necessary sparkling namespaces:
I fixed the issue by specifically requiring `[sparkling.serialization]` on a ns that was AOT compiled (the main class in my case). I suspect that was necessary because of the way the `sparkling.serialization.Registrator` classes are created in that ns?
