### ISSUE TITLE
Initial job has not accepted any resources – Clojure-specific Problem

### ISSUE THREAD

**Issue by rizo** [gorillalabs/sparkling#2]
Hi,

I have a standalone spark cluster running on my test machine (version 1.1.0 compiled from source without hadoop) and want to use it in a simple demo app with sparkling.

Here's a minimal source code that I used to reproduce the problem:

- <https://github.com/rizo/spark-playground/tree/master/spark-base/src/spark_base>

There are no other workers on the cluster using the memory. Here is the status of the cluster before the execution of the job:

![screen shot 2015-01-08 at 15 20 54](https://cloud.githubusercontent.com/assets/308413/5665306/739944a0-974f-11e4-8d42-624df0933683.png)

When I run the demo app, the following error is risen:

```
Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient memory.
```

(Full job logs: <https://gist.github.com/rizo/2662a1a4c81d1c572d09>)

After the submission, the application occupies all of the cores and uses 512mb and exits after 30 sec timeout:

![screen shot 2015-01-08 at 15 21 17](https://cloud.githubusercontent.com/assets/308413/5665376/e1a035f8-974f-11e4-86b6-aa7e2e7b0c83.png)

Initially I thought there was a problem with my cluster configuration, but spark-shell and pyspark are working without any problems. Also I successfully executed the job with spark-submit using the uberjar built with the same spark-base project.

What could be wrong here? Are there anything clojure-specific settings I have to set to run the app on the cluster?

Thanks in advance for your response!

**Comment by rizo** [comment]
@jqcorreia, keep updated on this.

**Comment by chrisbetz** [comment]
Hm, one thing I see in your log (http://188.166.34.149:18081/logPage/?appId=app-20150108153231-0000&executorId=0&logType=stderr) is that Exception... But I'm still on it.

**Comment by rizo** [comment]
Right! The strange thing is that it does run by submitting the uberjar:

```~/spark-1.1.0/bin/spark-submit --master spark://188.166.34.149:7077 --class spark_cassandra_demo.core target/uberjar/spark-cassandra-demo-0.1.0-SNAPSHOT-standalone.jar
```

Does it mean the problem has something to do with network or serialization?

**Comment by chrisbetz** [comment]
Are you running your driver on your local machine or on the cluster? If it's on your local machine: Can you reach driver-host/port combination from all cluaster machines? (see https://www.mail-archive.com/user@spark.apache.org/msg14656.html).

You can find the IP configured in your Spark WebUI (see console output from spark-submit) like this: 
    15/01/08 21:22:08 INFO ui.SparkUI: Started SparkUI at http://192.168.1.XXX:4040

If you go to 
    http://192.168.1.XXX:4040/environment/
you should find 
spark.driver.host	192.168.1.XXX
spark.driver.port	56673

For me, the 192.168.1.XXX is definitively not pingable from you cluster, thus resulting in that error.

**Comment by rizo** [comment]
I tried both, running it on the same machine where the cluster's master and worker are running and on my local machine.

And while it's true that, when I run the driver on my machine, it is not reachable, when I run it on the cluster it should be reachable.

Here's the env status when the app is running on the cluster:

![screen shot 2015-01-08 at 23 23 40](https://cloud.githubusercontent.com/assets/308413/5672961/fe56677e-978d-11e4-89b8-faa0be611fa1.png)

Both, spark master and the driver are on the same machine and network, and still I'm getting the "Initial job has not accepted any resources" warning and the job times out after several attempts.

Maybe it's some kind of permission problem?

**Comment by rizo** [comment]
I think I misunderstood how the driver should be launched. I tried to directly execute my code on the cluster's machine by invoking `lein repl` and providing the Spark's master URI.

I was convinced that it should work because I did exactly that in the shell (both in Scala and Python variants) by manually creating the conf and context and it worked. I did the same in Clojure's repl and was always getting the resources' problem I described initially.

By submitting the application with your instructions I was able to run the code and see the expected result. I still don't understand what was wrong with my initial approach and IMO the documentation is not very clear on this particular aspect. Also I found Spark's error messages (which appeared nondeterministically several times) hard to understand and debug, which made it difficult to locate the source of the problem.

If you don't have any further comments you may close the issue.
And thank you for your help! ;)

**Comment by chrisbetz** [comment]
Ok, I read some stuff on that issue - it appears under certain circumstances. In our case, I think it's based upon the fact, that the Spark Driver (inside the REPL) has no chance to serialize (all, some, a few) things over to the Workers. I think - without proving my hypotheses from source analysis or tests - that Spark is trying to get hold of classes based upon the URL of the jar given: A file:-URL is relative to the driver and transferred to the workers by a HTTP server. A local:-URL ... and an hdfs:-URL... you see the point: When starting the REPL with `lein repl, there's no jar to refer to.

I don't think there's an easy way out there. You could either start an nREPL from an uberjar and connect to it or stay on a "local" master.

So far, so good. I will start a new guide on this topic on http://gorillalabs.github.io/sparkling/ as soon as possible, but I will close this issue now.
