### ISSUE TITLE
Recompile function for REPL development

### ISSUE THREAD

**Issue by bucketh3ad** [gorillalabs/sparkling#26]
Since Spark requires functions to be compiled in order to work, I wrote a little helper function that aids REPL development by recompiling the current namespace.

`(defn recompile []
  (binding [*compile-files* true]
    (require (symbol (str *ns*)) :reload-all)))`

Not sure if this would fit in the project anywhere, but I found it useful for speeding up my workflow, particularly when connected to an nREPL from my editor. Calling `(recompile)` certainly beats booting up a new REPL and reconnecting.

**Comment by chrisbetz** [comment]
closing this, because working on that will be tracked in #36 . Thanks for the input.
