### ISSUE TITLE
subvectors don't serialize properly

### ISSUE THREAD

**Issue by retnuh** [gorillalabs/sparkling#34]
This works:

    (testing
      "we can serialize and deserialize vectors"
      (is (= [1 2 3 4 5]
             (ks/round-trip kryo [1 2 3 4 5]))))

But this does not, it fails with the exception included at the end:

    (testing
      "we can serialize and deserialize sub-vectors"
      (is (= [2 3 4]
             (ks/round-trip kryo (subvec [1 2 3 4 5] 1 4)))))

I tried registering IPersistentVector, IPersistentMap and APersistentVector$SubVector but that didn't help.  Don't know enough about how the serialization works to understand why vectors work as expected but subvectors don't.

Stack trace:

lein test :only sparkling.serialization-test/new-registrator

ERROR in (new-registrator) (APersistentVector.java:359)
we can serialize and deserialize sub-vectors
expected: (= [2 3 4] (ks/round-trip kryo (subvec [1 2 3 4 5] 1 4)))
  actual: java.lang.UnsupportedOperationException: null
 at clojure.lang.APersistentVector.add (APersistentVector.java:359)
    com.esotericsoftware.kryo.serializers.CollectionSerializer.read (CollectionSerializer.java:109)
    com.esotericsoftware.kryo.serializers.CollectionSerializer.read (CollectionSerializer.java:18)
    com.esotericsoftware.kryo.Kryo.readClassAndObject (Kryo.java:729)
    carbonite.buffer$read_bytes.invoke (buffer.clj:89)
    sparkling.kryoserializer$round_trip.invoke (kryoserializer.clj:15)
    sparkling.serialization_test/fn (serialization_test.clj:34)
    clojure.test$test_var$fn__7670.invoke (test.clj:704)
    clojure.test$test_var.invoke (test.clj:704)
    clojure.test$test_vars$fn__7692$fn__7697.invoke (test.clj:722)
    clojure.test$default_fixture.invoke (test.clj:674)
    clojure.test$test_vars$fn__7692.invoke (test.clj:722)
    clojure.test$default_fixture.invoke (test.clj:674)
    clojure.test$test_vars.invoke (test.clj:718)
    clojure.test$test_all_vars.invoke (test.clj:728)
    clojure.test$test_ns.invoke (test.clj:747)
    clojure.core$map$fn__4553.invoke (core.clj:2624)
    clojure.lang.LazySeq.sval (LazySeq.java:40)
    clojure.lang.LazySeq.seq (LazySeq.java:49)
    clojure.lang.Cons.next (Cons.java:39)
    clojure.lang.RT.next (RT.java:674)
    clojure.core/next (core.clj:64)
    clojure.core$reduce1.invoke (core.clj:909)
    clojure.core$reduce1.invoke (core.clj:900)
    clojure.core$merge_with.doInvoke (core.clj:2936)
    clojure.lang.RestFn.applyTo (RestFn.java:139)
    clojure.core$apply.invoke (core.clj:632)
    clojure.test$run_tests.doInvoke (test.clj:762)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    clojure.core$apply.invoke (core.clj:630)
    user$eval87$fn__146$fn__177.invoke (form-init6084764228854399442.clj:1)
    user$eval87$fn__146$fn__147.invoke (form-init6084764228854399442.clj:1)
    user$eval87$fn__146.invoke (form-init6084764228854399442.clj:1)
    user$eval87.invoke (form-init6084764228854399442.clj:1)
    clojure.lang.Compiler.eval (Compiler.java:6782)
    clojure.lang.Compiler.eval (Compiler.java:6772)
    clojure.lang.Compiler.load (Compiler.java:7227)
    clojure.lang.Compiler.loadFile (Compiler.java:7165)
    clojure.main$load_script.invoke (main.clj:275)
    clojure.main$init_opt.invoke (main.clj:280)
    clojure.main$initialize.invoke (main.clj:308)
    clojure.main$null_opt.invoke (main.clj:343)
    clojure.main$main.doInvoke (main.clj:421)
    clojure.lang.RestFn.invoke (RestFn.java:421)
    clojure.lang.Var.invoke (Var.java:383)
    clojure.lang.AFn.applyToHelper (AFn.java:156)
    clojure.lang.Var.applyTo (Var.java:700)
    clojure.main.main (main.java:37)

**Comment by retnuh** [comment]
Upon reflection, serializing out the base vector is probably the wrong thing, anyway.  

Pull request #35 sent.

**Comment by chrisbetz** [comment]
merged and released as 1.2.4
