### ISSUE TITLE
Creating a stand-alone jar file from Sparkling

### ISSUE THREAD

**Issue by gorjida** [gorillalabs/sparkling#38]
Hello,

I just cloned Sparkling package and tried to create a standalone jar file using lein uberjar; I see none of clojure files have a gen-class keyword; So, just for the test, I put a simple helloword.clj code in sparkling folder with the following command:
(ns sparkling.helloworld
(:gen-class)
)

(defn -main [& args]
(println "Hello, World!")
)

When I run lein uberjar, it creates jar file but does not generate any class for helloword.cli; There is just clj file in clojure/sparkling path; I also added :uberjat {:aot :all} to project.clj but the problem still exists; Is there any trick I have to apply to create the jar file? I probably want to run the Spark job on EMR cluster and, to do this, I need to be able to create a stand-alone JAR file with all dependencies; Your comments and advice would be really appreciated;

With best regards,

Ali

**Comment by retnuh** [comment]
I run on EMR, my project file looks more-or-less like this:

(defproject schtuff "0.1.0-SNAPSHOT"
  :description "whatever"
  :license {:name "The Apache License, Version 2.0"
            :url  "http://www.apache.org/licenses/LICENSE-2.0"}
  :dependencies [[org.clojure/clojure "1.8.0-RC3"]
                 [org.clojure/tools.cli "0.3.3"]
                 [org.clojure/tools.logging "0.3.1"]
                 [gorillalabs/sparkling "1.2.3"]
                 [instaparse "1.4.1"]
                 [clj-http "2.0.0"]
                 [org.clojure/core.cache "0.6.4"]
                 [clj-http "2.0.0"]
                 [clj-http-fake "1.0.1"]
                 [cheshire "5.5.0"]
                 [org.apache.spark/spark-mllib_2.10 "1.5.2"]
                 [org.apache.spark/spark-core_2.10 "1.5.2"]
                 [enlive "1.1.6"]
                 [clojure-csv/clojure-csv "2.0.1"]
                 [camel-snake-kebab "0.3.2"]
                 [com.github.fommil.netlib/all "1.1.2" :extension "pom"]
                 [environ "1.0.1"]
                 [pandect "0.5.4"]
                 ]

  :aot [clojure.tools.logging clojure.tools.logging.impl clojure-csv.core
        #".*"
        sparkling.serialization sparkling.destructuring sparkling.utils sparkling.core
        ]
  :jvm-opts ^:replace ["-server" "-Xmx12g"]
  :main schtuff.core
  :uberjar-merge-with {#"reference\.conf$" [slurp str spit]}
  :target-path "target/%s"
  :profiles {
             :uberjar {:auto-clean false}
             }
  )

Hope that helps!  I found the AOT thing can be a bit tricky with the ordering of classes, especially in the repl, but with the ordering I have above, I haven't had to fuss with it in ages, so it seems to be good.

**Comment by chrisbetz** [comment]
think I can close this now.
