### ISSUE TITLE
Parallelize argument problem in Getting Started document

### ISSUE THREAD

**Issue by Vaguery** [gorillalabs/sparkling#39]
I'm working through http://gorillalabs.github.io/sparkling/articles/getting_started.html on a Mac running OS X 10.11.3, fully updated `leiningen` systems, running Java 8 update 71, CLI REPL running in a bash.session. The same behavior seems to arise whether I use the `project.clj` file included with the download, or one I've modified to be

```clojure
(defproject gorillalabs/sparkling-getting-started "1.0.0-SNAPSHOT"
            :description "A Sample project demonstrating the use of Sparkling (https://gorillalabs.github.io/sparkling/), as shown in tutorial https://gorillalabs.github.io/sparkling/articles/tfidf_guide.html"
            :url "https://gorillalabs.github.io/sparkling/articles/tfidf_guide.html"
            :license {:name "Eclipse Public License"
                      :url  "http://www.eclipse.org/legal/epl-v10.html"}
            :dependencies [[org.clojure/clojure "1.8.0"]                      ;; changed
                           [gorillalabs/sparkling "1.2.3"]]

            :aot [#".*" sparkling.serialization sparkling.destructuring]
            :main tf-idf.core                                                    ;; VVVVV changed
            :profiles {:provided {:dependencies [[org.apache.spark/spark-core_2.10 "1.6.0"]]}
                       :dev {:plugins [[lein-dotenv "RELEASE"]]}})
```

Everything is fine (with some minor differences, apparently, in the return value annotations you report in your examples), until I get to

```text
tf-idf.core=> (def data (spark/parallelize sc [1 2 3 4 5] 4))
CompilerException java.lang.ClassCastException: Cannot cast java.lang.Long to java.util.List, compiling:(form-init6916667632007495202.clj:1:11)
```

I admit I'm not following the call chain up all the way through the variadic function calls, but it's pretty clear this stops being a problem when the numeric `slices` argument (`4` in the example) isn't present.

Are slices created on demand, or does the context need to have them defined before manually assigning a `slices` argument here? Unclear from the walkthrough.

**Comment by retnuh** [comment]
I've experienced that as well with what I've done, but never had time to fully track down what the problem was.  It wasn't anything obvious.

It is probably a problem with detecting variadic args; I don't know if this is a sparkling bug or a clojure one.

**Comment by Vaguery** [comment]
I may have some time later in the day to track this down. Since I'm only getting started, how often is this feature actually useful for the user to invoke manually, rather than relying on Spark's automatic balancing?

**Comment by retnuh** [comment]
There are definately times when data can be saved out with some random
number of partitions, and you want a more sane/regular/whatever set of
partitions.  It is theoretically more efficient to set the correct number
of partitions when you're loading it rather than load it and then
repartition it; but given the funky laziness of RDD things, it may not make
any difference at all!

**Comment by chrisbetz** [comment]
check :)
