### ISSUE TITLE
How to perform Secondary Sort?

### ISSUE THREAD

**Issue by punit-naik** [gorillalabs/sparkling#48]
I have the following scala code which I want to write using sparkling:
```
case class RFMCKey(cId: String, R: Double, F: Double, M: Double, C: Double)
class RFMCPartitioner(partitions: Int) extends Partitioner {
 require(partitions >= 0, "Number of partitions ($partitions) cannot be negative.")
 override def numPartitions: Int = partitions
 override def getPartition(key: Any): Int = {
 val k = key.asInstanceOf[RFMCKey]
 k.cId.hashCode() % numPartitions
 }
}
object RFMCKey {
 implicit def orderingByIdAirportIdDelay[A <: RFMCKey] : Ordering[A] = {
    Ordering.by(k => (k.R, k.F * -1, k.M * -1, k.C * -1))
 }
}
```
How can I do this? If I can, how do I use this for secondary sorting using sparkling? i.e. I want to perform `data.repartitionAndSortWithinPartitions(new RFMCPartitioner(partitions))`.

**Comment by chrisbetz** [comment]
Why don't you just use something like this:

```clojure
(proxy [HashPartitioner] [n]
    (getPartition [pdi]
...
))
```

Just see https://github.com/gorillalabs/sparkling/blob/master/src/clojure/sparkling/core.clj#L626 and following lines.
