### ISSUE TITLE
Can i join you organization?

### ISSUE THREAD

**Issue by chanshunli** [gorillalabs/sparkling#61]
Can i join you organization: https://github.com/gorillalabs ? 
I created this organization https://github.com/clojure-spark, but i hope i can develop for gorillalabs/sparkling. 
thanks :-)

**Comment by chrisbetz** [comment]
Hi,

thanks for the interest. I'm currently on vacation, but will check your request after my return.


Happy coding,

Chris

**Comment by nunesdaniel** [comment]
Hi, I would like to join gorillalabs/sparkling Community and Contribute to it.

**Comment by chrisbetz** [comment]
Hi,

I'd really appreciate help on sparkling. However, I would like to see contributions in the form of PRs first onboarding new people to gorillalabs.

So, feel free to fork sparkling, make contributions and re-apply later on :)

Happy hacking!

Chris
