### ISSUE TITLE
Support req: `take` can't be used with `map-to-pair`? [2.1.2]

### ISSUE THREAD

**Issue by hlship** [gorillalabs/sparkling#64]
I'm tooling up for some spark work; I've exported some data from Cassandra to a local file so I can test some of my logic in the REPL.

I'm hitting an initial problem:

```
(ns user
  (:require
    [sparkling.conf :as conf]
    [sparkling.core :as spark]
    [clojure.string :as str]))

(defn split-line
  [line]
  (let [pipex (str/index-of line \|)
        ruid (-> line
                 (subs 0 pipex)
                 str/trim)
        base64 (-> line
                   (subs (inc pipex))
                   str/trim)]
    (spark/tuple ruid base64)))

(comment

  (spark/with-context sc
                      (-> (conf/spark-conf)
                          (conf/master "local")
                          (conf/app-name "local-example"))
                      (->> (spark/text-file sc "receipts.txt")
                           (spark/take 2)
                           (spark/map-to-pair split-line)
                           #_ (spark/take 2)
                           ))

  )
```

fails with:

` java.lang.IllegalArgumentException: No matching method found: mapToPair for class scala.collection.convert.Wrappers$SeqWrapper`

It does work if I move the `take` call after the `map-to-pair` call.  As I understand things, the order of `take` vs. `map-to-pair` shouldn't make a difference.  Is that correct?  Am I seeing a bug.

Also, have you considered setting up in Clojurian's slack for support?

**Comment by chrisbetz** [comment]
Hello Howard,


take is a function returning data to the driver (here in the form of an array). It is not a function transforming an RDD to another RDD ("transformation") (see https://spark.apache.org/docs/2.1.0/api/scala/index.html#org.apache.spark.rdd.RDD <https://spark.apache.org/docs/2.1.0/api/scala/index.html#org.apache.spark.rdd.RDD>, look at ’take’), but a so called „action".

That’s the reason your code is failing - you’re trying to get an RDD (txt from file), take the first two lines in the driver and then the Spark Job is finished. If you want to run you spark job on a small subset of the original data, you should use sample or takeSample (again, see https://spark.apache.org/docs/2.1.0/api/scala/index.html#org.apache.spark.rdd.RDD <https://spark.apache.org/docs/2.1.0/api/scala/index.html#org.apache.spark.rdd.RDD>).

So, yes, you hit a bug - but not one in Sparkling nor in Apache Spark ;)

Maybe you want to check out https://www.slideshare.net/cb.betz/spark-and-clojure-2 <https://www.slideshare.net/cb.betz/spark-and-clojure-2> for an overview?

Sincerly,

Chris
