### ISSUE TITLE
Should we support Clojuresque parameter order?

### ISSUE THREAD

**Issue by chrisbetz** [gorillalabs/sparkling#7]
We just kept the parameter order from clj-spark and flambo to simplify migration. However, it could be more intuitive to not follow clj-spark, but to follow the Clojure way of parameter order.

E.g., (map function collection) -> (spark/map function rdd).

Idea is to have a separate namespace with functions working the clojure way, fading out support for the clj-spark way after a time of having both in parallel.

What do you think?

**Comment by tmoerman** [comment]
Intuitively I would prefer the coll to be the last argument and use the thread-last macro for chaining map/filter operations. Technically I'm not aware of any real pros/cons for either choice. 

At the end of the day, Sparkling is a Clojure API. Doing things the idiomatic Clojure way makes sense to me.

**Comment by rizo** [comment]
Completely agreed with @tmoerman.

I find myself rewriting the order of args each time I want to test simple algorithms in the repl or tests. Also, I'm planning to write a simple adapter API to optionally require spark (or native clojure functions), to separate deployment with spark and simple local testing of the algorithmic engine.

**Comment by chrisbetz** [comment]
Hi!

Thanks for your comments. Please check https://github.com/gorillalabs/sparkling/tree/clojuresque-api
* I added sparkling.core (as a new entry point) with clojuresque functions
* I rewired sparkling.api to refer to sparkling.core, so you could still use the old API, but under the hood it delegates everything to the new API.

If that's fine, I will merge this into master, create a new release and update guides and example projects. Any comments are welcome, feel free to open up pull requests ;)

**Comment by chrisbetz** [comment]
BTW: It's on Clojars as [gorillalabs/sparkling "1.1.0-SNAPSHOT"]

**Comment by chrisbetz** [comment]
Just released 1.1.0, no with a more clojuresque api as discussed.

**Comment by pesterhazy** [comment]
Great! Makes me happy.

**Comment by chrisbetz** [comment]
Hi, glad you like it. Consulting your adapter: are you sure a 'local' Spark Master isn't right for you? At least that's how I'm working.

Just check out the sparkling test suite.

Having an adapter is nice for different reasons though, but there's already an Apache project for that, targeting local, Spark or Hadoop M/R. Need to find the link if you're interested.

Cheers,
Chris
