### ISSUE TITLE
Unable to use mongo spark

### ISSUE THREAD

**Issue by binodsarkar** [gorillalabs/sparkling#71]
Unable to use spark with mongodb. Getting error
`Exception in thread "main" java.lang.ClassCastException: Cannot cast org.apache.spark.sql.SparkSession to org.apache.spark.api.java.JavaSparkContext, compiling:(spark_mongo.clj:30:9)`

My project settings:
`[org.mongodb.spark/mongo-spark-connector_2.11 "2.3.2"]
   [gorillalabs/sparkling "2.1.3"]`

Spark code:
`(ns etl.sparktest
  (:require [sparkling.conf :as conf]
            [sparkling.core :as spark])
  (:import (org.apache.spark.sql SparkSession)
           (com.mongodb.spark MongoSpark)))

(def sparks
  (->
    (SparkSession/builder)
    (.appName "MongoSparkConnectorIntro")
    (.master "local")
    (.config "spark.mongodb.input.uri", "mongodb://127.0.0.1/db.collection")
    (.config "spark.mongodb.output.uri", "mongodb://127.0.0.1/db.collection")
    .getOrCreate
    ))

(def df (MongoSpark/load (sparks)))`

**Comment by chrisbetz** [comment]
Hi,

not sure how this is a Sparkling issue, as you're not actually using it in your code example. I'm pretty sure you're not using MongoSpark/load properly, as this expects a JavaSparkContext instance, not a SparkSession object.

MongoSpark/load method (on https://www.javadoc.io/doc/org.mongodb.spark/mongo-spark-connector_2.11/2.3.2) with just one parameter expects a JavaSparkContext. You might want to use one of the other load methods which accept a SparkSession?

Cheers,

Chris

**Comment by binodsarkar** [comment]
Hi chrisbetz,
Thanks for your reply. Yes you are correct. Silly mistake. Thank you again for your help.
