### ISSUE TITLE
Connecting to s3n uri with authentication failing

### ISSUE THREAD

**Issue by jclavijo** [gorillalabs/sparkling#74]
I'm facing an error while trying to connect to an s3 bucket. I'm using
(conf/set "fs.s3.awsAccessKeyId" ....) to set the accesskey and the secretKey but I'm getting this error.
Execution error (IllegalArgumentException) at org.apache.hadoop.fs.s3.S3Credentials/initialize (S3Credentials.java:70).
AWS Access Key ID and Secret Access Key must be specified as the username or password (respectively) of a s3n URL, or by setting the fs.s3n.awsAccessKeyId or fs.s3n.awsSecretAccessKey properties (respectively).

**Comment by chrisbetz** [comment]
Hi Juan-Manuel,

unfortunately, I'm not using S3 with Sparkling, so I can't help you here. As this is not directly a Sparkling issue I'd like to close this issue for now. However, if you find a way, please feel free to add a comment, as others might also stumble into this.

Cheers,

Chris

**Comment by jclavijo** [comment]
I'll leave any information if there are findings but in the manual there are mentions of using text-file s3n:// urls  https://gorillalabs.github.io/sparkling/articles/getting_started.html#external_datasets

**Comment by retnuh** [comment]
It's been a good few years, but I used s3 with Sparkling.  I seem to recall that the correct url to use is `s3://`, not `s3n://` or `s3a://` - those were in use for awhile but all the desirable functionality got folded back into the S3 url handler.  I vaguely recall problems trying to get `s3n` to work and found that `s3` ended up working much better.
